GITHUB_ACTIONS_USERNAME = 'github_actions'
LAMBDA_PROXY_AUTH_USERNAME = 'schedule'
DEFAULT_ENTRYPOINT = 'function.py'
DEFAULT_REQUIREMENTS = 'requirements.txt'
DEFAULT_CRON_SCHEDULE = "0 0 * * *"
ARCHIVE_EXTENSION = "tar.gz"
