version: "3.8"

services:

  # Server
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: seamless-server
    volumes:
      - .:/src
    mem_limit: 128m
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    command: "gunicorn -w 4 -b 0.0.0.0:5000 \
              --timeout 120 \
              --log-level=info \
              --capture-output \
              --enable-stdio-inheritance \
              application:app \
              --reload"

  # UI
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: seamless-client
    volumes:
      - ./client/src:/src/client/src
      - ./static:/src/static
    mem_limit: 128m

  # Alembic
  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    image: seamless-migration
    entrypoint: ""
    command: "bash"
    env_file: .env
    volumes:
      - .:/src
    mem_limit: 128m
    depends_on:
      - postgres

  # Database
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./postgres_healthcheck.sh:/src/postgres_healthcheck.sh
      - ./sql_scripts/db_seamless_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    mem_limit: 128m
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "bash", "src/postgres_healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
