import os

AUTH0_BASE_URL = os.getenv('AUTH0_BASE_URL')
AUTH0_WEB_API_AUDIENCE = os.getenv('AUTH0_WEB_API_AUDIENCE')
AUTH0_CLIENT_ID = os.getenv('AUTH0_CLIENT_ID')
AUTH0_CLIENT_SECRET = os.getenv('AUTH0_CLIENT_SECRET')
AUTH0_CALLBACK_URL = os.getenv('AUTH0_CALLBACK_URL')
SCHEDULE_PASSWORD = os.getenv('SCHEDULE_PASSWORD')
SENTRY_DSN = os.getenv('SENTRY_DSN')
