"""

Revision ID: 101b182bd0ce
Revises: 3aecef07d21a
Create Date: 2020-07-15 15:13:13.020740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101b182bd0ce'
down_revision = '3aecef07d21a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_type', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_type')
    # ### end Alembic commands ###
