"""

Revision ID: 3aecef07d21a
Revises: f7866c904dec
Create Date: 2020-07-06 12:33:10.248491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aecef07d21a'
down_revision = 'f7866c904dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', '_cloudwatch_rule_arn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('_cloudwatch_rule_arn', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
