"""

Revision ID: 5077128d8e96
Revises: 783e230bc89f
Create Date: 2020-10-03 00:48:11.743491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5077128d8e96'
down_revision = '783e230bc89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('plan_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'jobs', 'job_plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'plan_id')
    # ### end Alembic commands ###
