"""

Revision ID: 5f2a1e7f076c
Revises: 5077128d8e96
Create Date: 2020-10-03 01:29:07.785670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2a1e7f076c'
down_revision = '5077128d8e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_plans', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_plans', 'active')
    # ### end Alembic commands ###
