"""

Revision ID: 656da55dad04
Revises: 2b98d9a803e6
Create Date: 2020-10-02 09:49:49.085872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656da55dad04'
down_revision = '2b98d9a803e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('stripe_subscription_id', sa.Text(), nullable=True),
    sa.Column('paid_until', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('stripe_id', sa.Text(), nullable=True))
    op.add_column('workspaces', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workspaces', 'workspace_plans', ['plan_id'], ['id'])
    op.drop_column('workspaces', 'plan')
    op.drop_column('workspaces', 'subscription_is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('subscription_is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('workspaces', sa.Column('plan', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_column('workspaces', 'plan_id')
    op.drop_column('users', 'stripe_id')
    op.drop_table('workspace_plans')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
