"""

Revision ID: 705f2d9a4823
Revises: 2b98d9a803e6
Create Date: 2020-09-29 14:01:17.274115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705f2d9a4823'
down_revision = '2b98d9a803e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'invitations', ['id'])
    op.add_column('users', sa.Column('stripe_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripe_id')
    op.drop_constraint(None, 'invitations', type_='unique')
    # ### end Alembic commands ###
