"""

Revision ID: 74e158eb1678
Revises: 9e3070bd7c87
Create Date: 2020-09-17 11:53:09.709432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e158eb1678'
down_revision = '9e3070bd7c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('subscription_is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('job_names_must_be_unique_within_workspace', 'jobs', ['workspace_id', 'name'])
    op.drop_constraint('job_names_must_be_unique_within_user', 'jobs', type_='unique')
    op.create_foreign_key(None, 'jobs', 'workspaces', ['workspace_id'], ['id'])
    op.drop_column('users', 'account_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_type', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_unique_constraint('job_names_must_be_unique_within_user', 'jobs', ['user_id', 'name'])
    op.drop_constraint('job_names_must_be_unique_within_workspace', 'jobs', type_='unique')
    op.drop_column('jobs', 'workspace_id')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
