"""

Revision ID: 783e230bc89f
Revises: 2b98d9a803e6
Create Date: 2020-10-03 00:35:50.303936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783e230bc89f'
down_revision = '2b98d9a803e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('stripe_subscription_id', sa.Text(), nullable=True),
        sa.Column('paid_until', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_plans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('subscription_id', sa.Integer(), nullable=True),
        sa.Column('job_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
        sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_charges',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('plan_id', sa.Integer(), nullable=True),
        sa.Column('price', sa.Numeric(), nullable=True),
        sa.Column('payed', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['plan_id'], ['job_plans.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_plans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('subscription_id', sa.Integer(), nullable=True),
        sa.Column('workspace_id', sa.Integer(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_charges',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('plan_id', sa.Integer(), nullable=True),
        sa.Column('price', sa.Numeric(), nullable=True),
        sa.Column('payed', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['plan_id'], ['workspace_plans.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('stripe_id', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'subscriptions', ['subscription_id'], ['id'])
    op.add_column('workspaces', sa.Column('personal', sa.Boolean(), nullable=True))
    op.add_column('workspaces', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workspaces', 'workspace_plans', ['plan_id'], ['id'])
    op.drop_column('workspaces', 'plan')
    op.drop_column('workspaces', 'subscription_is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('subscription_is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('workspaces', sa.Column('plan', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_column('workspaces', 'plan_id')
    op.drop_column('workspaces', 'personal')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'subscription_id')
    op.drop_column('users', 'stripe_id')
    op.drop_table('workspace_plans')
    op.drop_table('workspace_charges')
    op.drop_table('subscriptions')
    op.drop_table('job_plans')
    op.drop_table('job_charges')
    # ### end Alembic commands ###
