"""logs_in_postgres

Revision ID: 82045e42b0bd
Revises: 9f64c94b9631
Create Date: 2020-07-01 07:39:55.049717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82045e42b0bd'
down_revision = '9f64c94b9631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_run_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_run_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_run_logs_timestamp'), 'job_run_logs', ['timestamp'], unique=False)
    op.drop_column('job_runs', 'cloudwatch_log_stream_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_runs', sa.Column('cloudwatch_log_stream_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_job_run_logs_timestamp'), table_name='job_run_logs')
    op.drop_table('job_run_logs')
    # ### end Alembic commands ###
