"""

Revision ID: 822aebd299cb
Revises: 943010596e91
Create Date: 2020-08-06 12:12:06.218330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822aebd299cb'
down_revision = '943010596e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_runs', 'status',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_runs', 'status',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
