"""

Revision ID: 95785a984b74
Revises: 74e158eb1678
Create Date: 2020-09-18 11:32:11.459143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95785a984b74'
down_revision = '74e158eb1678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'created_at')
    # ### end Alembic commands ###
