"""logstream_name_column

Revision ID: 9f64c94b9631
Revises: 2c43896c8271
Create Date: 2020-06-30 14:31:01.060606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f64c94b9631'
down_revision = '2c43896c8271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_runs', sa.Column('cloudwatch_log_stream_name', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_runs', 'cloudwatch_log_stream_name')
    # ### end Alembic commands ###
