"""

Revision ID: a979b4dfd274
Revises: 2b98d9a803e6
Create Date: 2020-09-29 22:40:40.415051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a979b4dfd274'
down_revision = '2b98d9a803e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'invitations', ['id'])
    op.add_column('users', sa.Column('stripe_id', sa.Text(), nullable=True))
    op.add_column('workspaces', sa.Column('stripe_subscription_id', sa.Text(), nullable=True))
    op.add_column('workspaces', sa.Column('subscription_end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'subscription_end_date')
    op.drop_column('workspaces', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_id')
    op.drop_constraint(None, 'invitations', type_='unique')
    # ### end Alembic commands ###
