"""

Revision ID: bc96ee1366eb
Revises: 291fcbbed56d
Create Date: 2020-10-04 23:09:45.381515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc96ee1366eb'
down_revision = '291fcbbed56d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('job_parameters_job_id_fkey', 'job_parameters', type_='foreignkey')
    op.create_foreign_key('job_parameters_job_id_fkey', 'job_parameters', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('job_run_logs_job_run_id_fkey', 'job_run_logs', type_='foreignkey')
    op.create_foreign_key('job_run_logs_job_run_id_fkey', 'job_run_logs', 'job_runs', ['job_run_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('job_runs_job_id_fkey', 'job_runs', type_='foreignkey')
    op.create_foreign_key('job_runs_job_id_fkey', 'job_runs', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_jobs_workspace_id_workspaces', 'jobs', type_='foreignkey')
    op.create_foreign_key('fk_jobs_workspace_id_workspaces', 'jobs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_jobs_workspace_id_workspaces', 'jobs', type_='foreignkey')
    op.create_foreign_key('fk_jobs_workspace_id_workspaces', 'jobs', 'workspaces', ['workspace_id'], ['id'])
    op.drop_constraint('job_runs_job_id_fkey', 'job_runs', type_='foreignkey')
    op.create_foreign_key('job_runs_job_id_fkey', 'job_runs', 'jobs', ['job_id'], ['id'])
    op.drop_constraint('job_run_logs_job_run_id_fkey', 'job_run_logs', type_='foreignkey')
    op.create_foreign_key('job_run_logs_job_run_id_fkey', 'job_run_logs', 'job_runs', ['job_run_id'], ['id'])
    op.drop_constraint('job_parameters_job_id_fkey', 'job_parameters', type_='foreignkey')
    op.create_foreign_key('job_parameters_job_id_fkey', 'job_parameters', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###
