"""

Revision ID: d09ae02e17a5
Revises: bc96ee1366eb
Create Date: 2020-10-05 20:20:21.132936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09ae02e17a5'
down_revision = 'bc96ee1366eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('customer_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'customer_id')
    # ### end Alembic commands ###
