"""

Revision ID: e334781590f1
Revises: 9e3070bd7c87
Create Date: 2020-09-20 20:18:40.373499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e334781590f1'
down_revision = '9e3070bd7c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_templates', sa.Column('parameters', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_templates', 'parameters')
    # ### end Alembic commands ###
