"""

Revision ID: e58765978b3b
Revises: 951e3f4e8d47
Create Date: 2020-07-21 07:45:37.298654

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58765978b3b'
down_revision = '951e3f4e8d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(), nullable=False,
                                    server_default=datetime.utcnow().isoformat()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'updated_at')
    # ### end Alembic commands ###
