"""

Revision ID: f7866c904dec
Revises: 1458cf500152
Create Date: 2020-07-05 14:38:18.333494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7866c904dec'
down_revision = '1458cf500152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('_cloudwatch_rule_arn', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', '_cloudwatch_rule_arn')
    # ### end Alembic commands ###
