name: CI_CD

env:
  EB_PACKAGE_S3_BUCKET_NAME : "web-prod-packages"
  EB_APPLICATION_NAME       : "web-prod"
  EB_ENVIRONMENT_NAME       : "web-prod-env"
  DEPLOY_PACKAGE_NAME       : "web_prod_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-1"

on:
  push:
    branches: [ master ]

jobs:

  build_and_push_server_image:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - uses: kciter/aws-ecr-action@v1

      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: web-prod
        region: ${{ env.AWS_REGION_NAME }}
        tags: web-prod-server
        dockerfile: Dockerfile.server

  update_application:

    runs-on: ubuntu-latest
    needs: [build_and_push_server_image]

    steps:

      - uses: actions/checkout@v2

      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} Dockerrun.aws.json

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Upload package to S3 bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APPLICATION_NAME }} \
          --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "ver-${{ github.sha }}"
