name: CI_CD

env:
  AWS_REGION_NAME           : "us-east-1"

on:
  push:
    branches: [ master ]

jobs:

  build_and_push_server_image:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - uses: kciter/aws-ecr-action@v1

      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: my-web-app
        region: ${{ env.AWS_REGION_NAME }}
        tags: web-server
        dockerfile: Dockerfile.server
