name: Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check docker
        run: docker ps -aa
